#!/usr/bin/env node
/**
 * Points this checkout at the local Supabase stack.
 *
 * Reads the credentials `npm run db:start` printed and writes them to
 * `.env.local`, which Vite loads with higher precedence than `.env`. So:
 *
 *   npm run db:env        → the app talks to the local stack
 *   rm .env.local         → the app talks back to whatever `.env` points at
 *
 * `.env.local` is gitignored. The local keys are fixed demo values that every
 * Supabase CLI install shares — they are not secrets, but there is no reason
 * to commit them either.
 */
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { z } from 'zod';

const OUT_FILE = '.env.local';

/**
 * A field this script can use, or nothing.
 *
 * `.catch(undefined)` rather than a bare `.optional()`: a CLI version that
 * emits `null` for a key it no longer populates should fall through to the
 * next spelling below, not fail the whole parse.
 */
const optionalValue = () => z.string().min(1).optional().catch(undefined);

/**
 * The shape this script needs out of `supabase status -o json`, parsed at the
 * boundary so everything downstream is a known domain value.
 *
 * Key names have moved around across CLI versions, and the publishable/secret
 * pair only exists on newer ones, so each spelling is declared and the reads
 * below take the first one this CLI actually emitted. `z.object()` strips
 * every other key, which is the rest of the status payload.
 */
const statusSchema = z.object({
	API_URL: optionalValue(),
	api_url: optionalValue(),
	PUBLISHABLE_KEY: optionalValue(),
	ANON_KEY: optionalValue(),
	anon_key: optionalValue(),
	SECRET_KEY: optionalValue(),
	SERVICE_ROLE_KEY: optionalValue(),
	service_role_key: optionalValue()
});

let raw;
try {
	raw = execFileSync('npx', ['supabase', 'status', '-o', 'json'], {
		encoding: 'utf8',
		stdio: ['inherit', 'pipe', 'pipe']
	});
} catch {
	console.error(
		'Could not read the local stack status.\n' +
			'Start it first with `npm run db:start` (Docker must be running).'
	);
	process.exit(1);
}

let parsed;
try {
	parsed = statusSchema.safeParse(JSON.parse(raw));
} catch {
	console.error(`Could not parse \`supabase status -o json\`:\n${raw}`);
	process.exit(1);
}

if (!parsed.success) {
	console.error(`\`supabase status -o json\` was not the expected shape:\n${raw}`);
	process.exit(1);
}

const status = parsed.data;
const url = status.API_URL ?? status.api_url;
// Newer CLIs mint sb_publishable_/sb_secret_ keys; older ones only the JWTs.
// Either works with @supabase/ssr, so prefer the modern pair and fall back.
const publishableKey = status.PUBLISHABLE_KEY ?? status.ANON_KEY ?? status.anon_key;
const serviceRoleKey = status.SECRET_KEY ?? status.SERVICE_ROLE_KEY ?? status.service_role_key;

if (!url || !publishableKey) {
	console.error(
		'The stack is running but did not report an API URL and key.\n' +
			'Run `npm run db:status` and copy the values into .env.local by hand:\n' +
			`${JSON.stringify(status, null, 2)}`
	);
	process.exit(1);
}

const lines = [
	'# Generated by `npm run db:env` — points this checkout at the local stack.',
	'# Vite loads this after .env, so it wins. Delete it to go back to .env.',
	'# Regenerate after `npm run db:start` if the ports or keys ever change.',
	'',
	`PUBLIC_SUPABASE_URL=${url}`,
	`PUBLIC_SUPABASE_PUBLISHABLE_KEY=${publishableKey}`
];

if (serviceRoleKey) {
	lines.push(
		'',
		'# Local service-role key — bypasses RLS. Fine here; it only unlocks the',
		'# throwaway database on your own machine. Enables DEV_AUTO_LOGIN and',
		'# createSupabaseAdminClient().',
		`SUPABASE_SERVICE_ROLE_KEY=${serviceRoleKey}`
	);
}

writeFileSync(OUT_FILE, `${lines.join('\n')}\n`);
console.log(`Wrote ${OUT_FILE} → ${url}`);
console.log('Sign in as dev@example.com / password123.');
