#!/usr/bin/env node
/**
 * Points this checkout at the local Supabase stack.
 *
 * Reads the credentials `npm run db:start` printed and writes them to
 * `.env.local`, which Vite loads with higher precedence than `.env`. So:
 *
 *   npm run db:env        → the app talks to the local stack
 *   rm .env.local         → the app talks back to whatever `.env` points at
 *
 * `.env.local` is gitignored. The local keys are fixed demo values that every
 * Supabase CLI install shares — they are not secrets, but there is no reason
 * to commit them either.
 */
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

const OUT_FILE = '.env.local';

/**
 * `supabase status -o json` key names have moved around across CLI versions
 * (and the publishable/secret pair only exists on newer ones), so take the
 * first key that is actually present rather than pinning to one spelling.
 */
function pick(status, candidates) {
	for (const key of candidates) {
		const value = status[key];
		if (typeof value === 'string' && value.length > 0) return value;
	}
	return null;
}

let raw;
try {
	raw = execFileSync('npx', ['supabase', 'status', '-o', 'json'], {
		encoding: 'utf8',
		stdio: ['inherit', 'pipe', 'pipe']
	});
} catch {
	console.error(
		'Could not read the local stack status.\n' +
			'Start it first with `npm run db:start` (Docker must be running).'
	);
	process.exit(1);
}

let status;
try {
	status = JSON.parse(raw);
} catch {
	console.error(`Could not parse \`supabase status -o json\`:\n${raw}`);
	process.exit(1);
}

const url = pick(status, ['API_URL', 'api_url', 'apiUrl']);
// Newer CLIs mint sb_publishable_/sb_secret_ keys; older ones only the JWTs.
// Either works with @supabase/ssr, so prefer the modern pair and fall back.
const publishableKey = pick(status, ['PUBLISHABLE_KEY', 'ANON_KEY', 'anon_key']);
const serviceRoleKey = pick(status, ['SECRET_KEY', 'SERVICE_ROLE_KEY', 'service_role_key']);

if (!url || !publishableKey) {
	console.error(
		'The stack is running but did not report an API URL and key.\n' +
			'Run `npm run db:status` and copy the values into .env.local by hand:\n' +
			`${JSON.stringify(status, null, 2)}`
	);
	process.exit(1);
}

const lines = [
	'# Generated by `npm run db:env` — points this checkout at the local stack.',
	'# Vite loads this after .env, so it wins. Delete it to go back to .env.',
	'# Regenerate after `npm run db:start` if the ports or keys ever change.',
	'',
	`PUBLIC_SUPABASE_URL=${url}`,
	`PUBLIC_SUPABASE_PUBLISHABLE_KEY=${publishableKey}`
];

if (serviceRoleKey) {
	lines.push(
		'',
		'# Local service-role key — bypasses RLS. Fine here; it only unlocks the',
		'# throwaway database on your own machine. Enables DEV_AUTO_LOGIN and',
		'# createSupabaseAdminClient().',
		`SUPABASE_SERVICE_ROLE_KEY=${serviceRoleKey}`
	);
}

writeFileSync(OUT_FILE, `${lines.join('\n')}\n`);
console.log(`Wrote ${OUT_FILE} → ${url}`);
console.log('Run `npm run dev` and sign in as dev@example.com / password123.');
