-- Invoices become a kind of CRM record (the invoicing migration that follows
-- creates the tables). The enum value ships alone here because Postgres
-- refuses to use a value in the transaction that added it, exactly as the
-- party-model migration explains — the next file adds the tables and the
-- `private.crm_entity_exists()` branch that makes the value resolvable.
--
-- An invoice earns a place on the shared link the way a purchase order does:
-- you log the call chasing it (an activity), you tag the ones in dispute, and
-- a bill-to address is an address like any other.
--
-- `payments` deliberately does NOT join the enum. A payment is a ledger row,
-- not a record anyone annotates — what people have to say about the money is
-- said on the invoice it settles.
--
-- `before 'product'` keeps the enum in alphabetical order (… deal, invoice,
-- product …), which is the order the generated types list it in.
alter type public.crm_entity_type add value if not exists 'invoice' before 'product';
